AWSRegion: "ca-central-1"
CognitoClientID: ""
CognitoPoolID: ""
CognitoRegion: ""
# GraphqlURI: "http://120.0.0.1:3101/"
S3Bucket: "gsales-xls-reports"
S3FilePrefix: "reports"
SsmPath: "gsales-xls-reports"
Stage: "prod"